### ISSUE TITLE
What is missing in Sapper when compared to Gatsbyjs for JAM stack?

### ISSUE THREAD

**Issue by kaushalyap** [sveltejs/sapper#1093]
I hope someone create a checklist of what is missing in Sapper when compared Gatsbyjs for JAM stack in order to keep track of progress.

**Comment by andriijas** [comment]
I agree. Something like gatsby (react)  or Gridsome (vue) for svelte would make it really interesting to build something with. I like the idea of  hooking up data with plugins, generate static html and adding dynamic on top where needed. And if that dynamic part is also precompiled without any runtime library. Well then Im in cloud heaven 😂

**Comment by antony** [comment]
It sounds like the two of you are best placed to give an idea of what is missing! It could certainly be a good base for a roadmap of sorts for Sapper.

**Comment by kaushalyap** [comment]
@andriijas Can you please create a checklist? I could fill in if something is missing.

**Comment by sw-yx** [comment]
just linking my project here https://github.com/sw-yx/ssg as well as https://github.com/sveltejs/sapper/pulls/nealalpert

**Comment by andriijas** [comment]
- [ ] Pre-rendered HTML
- [ ] Automatic Code Splitting
- [ ] Follows PRPL-pattern
- [ ] Smart link prefetching
- [ ] Progressive Images
- [ ] Plugin architecture 
- [ ] "Bring your own data"
- [ ] Graphql layer

**Comment by bummzack** [comment]
Merging #869 would be a great first step. It would turn a broken system into a working one. 
This issue alone is stopping us from considering svelte/sapper for any future projects at the moment.

**Comment by kaushalyap** [comment]
In addition to what @andriijas mentioned

- [ ] PWA support
- [ ] Authentication ex: [authentication in gatsbyjs](https://www.gatsbyjs.org/docs/building-a-site-with-authentication/#implementing-authentication-in-a-gatsby-site)
- [ ] Security baked in, avoiding things like https://github.com/gatsbyjs/gatsby/issues/10890
- [ ] Themes ex: [gatsbyjs themes](https://www.gatsbyjs.org/docs/plugins-themes-and-starters/#what-is-a-theme)
- [ ] Incremental builds


Related issues from the repo

- [ ] Hook to generate 404 pages for `sapper export` : https://github.com/sveltejs/sapper/issues/557
- [ ] Static site optimizations: https://github.com/sveltejs/sapper/issues/172
- [ ] Better prefetch cache? https://github.com/sveltejs/sapper/issues/483 
- [ ] Prioritise prefetching: https://github.com/sveltejs/sapper/issues/59
- [ ] Preload all Route assets: https://github.com/sveltejs/sapper/issues/70
- [ ] PWA Install prompt not showing anymore: https://github.com/sveltejs/sapper/issues/754
- [ ] Image Processing Brainstorm: https://github.com/sveltejs/sapper/issues/897
- [ ] Feature Request: Automatic Build Time Static Optimization: https://github.com/sveltejs/sapper/issues/1046
- [ ] Inline main.js: https://github.com/sveltejs/sapper/issues/12

For image optimization there is [svelte-image]( https://github.com/matyunya/svelte-image) by @sw-yx

**Comment by hangtwenty** [comment]
Chipping in - it is not a Golden Hammer, but it could be worthwhile to have a compatibility bridge and/or conversion checklist/tool for "porting" Gatsby plugins (and/or React components more generally) to work with Svelte.

I'm sure that's not even possible for a bunch of cases and would amount to a rewrite. But for a given component, there's probably an implicit flow-chart/checklist in the head of someone who knows both frameworks. Maybe that could be made explicit.

Even if it just helps to identify a few areas of code that can be reused/ported, vs what code to rewrite. Maybe it's just an informal checklist or guide, maybe there's something that could be done with a static analysis tool.

Humbly submitted as someone relatively new to these frameworks. (I've always skewed towards backend, Svelte is the first JS framework that makes me excited about frontend again and truly enjoy working with it).

**Comment by hangtwenty** [comment]
p.s. maybe that idea would not even need to be good enough for producing "great" results but could just output a MVP or "reference implementation," but maybe still results in it being easier to tackle doing a port/redo in Svelte

**Comment by sw-yx** [comment]
i know both well. i'd say a subset of gatsby plugins can be adapted with low pain to work with sapper. the rest are unfortunately too React specific. would need adapters, or a "react mode".

**Comment by sw-yx** [comment]
linking https://github.com/sveltejs/sapper/issues/1110

**Comment by arxpoetica** [comment]
@andriijas Sapper does automatic code splitting and link prefetch

**Comment by janat08** [comment]
Routify is alternative to sapper.

**Comment by kaushalyap** [comment]
Does team any plans related to this? I hope they prioritize this.

**Comment by antony** [comment]
@kaushalyap it's certainly on our RoadMap, but as with anything, we will always welcome somebody from the community to spearhead and push this forward.

**Comment by GitGangGuy** [comment]
Another suggestion that applies to sapper in general but especially for static sites which are built for speed:

- [ ] Minification of ALL html (ssr html literals etc. which can still be found unminified in the exported output)

**Comment by hangtwenty** [comment]
[ side note ... @sw-yx could you edit your comment since the project is defunct? I will say: thank you, though! I learned about elderjs via your comment, and i'm going to try that for another project (while still using sapper in another case) ]
